#! /bin/sh

# spaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# config
bspc config window_gap 0
bspc config border_width 0
bspc config split_ratio 0.50
bspc config focus_follows_pointer true

# rules
bspc rule -a Code desktop='^2' follow=on focus=on
bspc rule -a firefox desktop='^3' follow=on focus=on
bspc rule -a Spotify desktop='^6' follow=on focus=on

# floating Apps
declare -a floatingApps=(xdman-Main Lxappearance Gparted Thunar \ 
Viewnior Xarchiver Pavucontrol firefox:Dialog firefox:Browser \
firefox:Pop-up nitrogen Gpick)
for i in ${floatingApps[@]}; do
    bspc rule -a $i state=floating focus=on follow=on; done

# autostart
pgrep -x sxhkd >/dev/null || sxhkd &
~/.config/polybar/launch.sh --grayblocks
